name: Enviar Ranking para o Discord

# Configura o gatilho: roda todo dia a cada 12 horas
on:
  schedule:
    - cron: '0 */12 * * *' 
  workflow_dispatch: # Permite que você clique num botão pra rodar manualmente

jobs:
  print_e_envio:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Rodar o script
        run: python script.py