name: Enviar Ranking para o Discord

on:
  schedule:
    - cron: '0 */12 * * *' 
  workflow_dispatch: 

jobs:
  print_e_envio:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v4 # <-- Atualizado aqui

      - name: Configurar Python
        uses: actions/setup-python@v5 # <-- Atualizado aqui
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Rodar o script
        run: python script.py
